services:
  - type: web
    name: car-service-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT --workers 1"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: RENDER_EXTERNAL_URL
        sync: false
      - key: OWNER_CHAT_ID
        sync: false
      - key: PYTHON_VERSION
        value: 3.12.0
